//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""ButtonActions"",
            ""id"": ""a7f26d43-ca3e-4aca-9248-99362d0010c6"",
            ""actions"": [
                {
                    ""name"": ""powerupaction"",
                    ""type"": ""PassThrough"",
                    ""id"": ""421b8609-13e1-4749-8cf0-f0aa2ab731d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""trackBall"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b4029cdc-7c4e-4be4-af75-0dfb40ccb394"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""Value"",
                    ""id"": ""3fc4d3e3-0bbe-4c81-8d15-fdf2c83f67a7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""powerupaction2"",
                    ""type"": ""Button"",
                    ""id"": ""75d00f2c-d190-4f8a-ad48-392ba3ff4ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""driftbar"",
                    ""type"": ""Button"",
                    ""id"": ""2037763c-0abf-46fd-ba65-8225675ac4b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""driftbar2"",
                    ""type"": ""Button"",
                    ""id"": ""d07662cc-fa04-4c67-a42b-2d9931b365bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moving"",
                    ""type"": ""Value"",
                    ""id"": ""24eae9dd-3d6f-461d-952d-a394132dc575"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""moving2"",
                    ""type"": ""Value"",
                    ""id"": ""d7a5af90-2181-4c09-8b32-32b687707c5b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""pause"",
                    ""type"": ""Button"",
                    ""id"": ""bb89a99d-7ce2-4163-8640-16567146bfbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rocket"",
                    ""type"": ""Button"",
                    ""id"": ""7d5e5510-dcf8-4604-8530-a58752f7244b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rocket2"",
                    ""type"": ""Button"",
                    ""id"": ""7d2d8f79-1a83-46f7-bd26-02b8d1d028c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""submit"",
                    ""type"": ""Button"",
                    ""id"": ""8d28903d-d2c9-4a7c-b33f-640e3fdb9121"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29a7c631-783c-472f-bfbe-2e836cb77930"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9f50701-9dad-4ee6-86f7-ac18290617de"",
                    ""path"": ""<SwitchProControllerHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f797cb0-7c06-49d5-a3bb-da5bc7f336a7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9ddad06-bde9-499f-b46a-6d44468a3440"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a95f3e-334a-4737-8936-52e3887155c2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""334ff061-416d-4509-ae08-c24c1d5735e0"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b37dbd39-787e-4df3-9191-25138f7798cf"",
                    ""path"": ""<SwitchProControllerHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8109c364-96f0-4071-8054-06c82fd3f8c3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f027d046-6a79-4151-b1bb-6082b3ab3ddf"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7674ac39-783d-4c5a-b6dd-f2e38aa0c7a7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ed723dc-08e4-4d78-90ca-2f79b977f0a4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""494ca615-96da-4647-bb10-ad76a2d9d86c"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5ebd891f-eba1-469d-89f2-3595234a5217"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""25f94f4e-3255-40ca-beaf-5b2fb5186e07"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bab2d4b6-1c7b-4c3d-ac4b-34f308304878"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2865de7c-cd10-4efb-a64e-f87a042bbaa2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b6b2ea75-da7c-4ced-a4c5-c312dfe27957"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""476269e4-21a4-442f-8eda-72df4ca673ba"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50d8d104-d95e-4b51-b333-93c5de3be8fa"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9201907d-4a43-4e30-8f14-1aa6b37182b3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70ae3a56-c1b7-42a8-bdbc-83db8c7b2b30"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba4b1aae-e873-452b-b5b1-add0ba684a56"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7322dcd8-adc6-4d5d-b989-c94ec7478552"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6164db55-71a5-491c-b8b7-33b52427a695"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74869ff1-fc8e-49b4-909d-1ee860a4fe43"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30840917-33d7-40dc-804e-95183afde131"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ff644ad-e607-4c25-8253-9ae8cb609bad"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d58a777-2809-4afc-aa65-0ebb569d311c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5af59410-d30e-4667-a397-0d0ea327a452"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""661161b0-5441-4088-8ae8-be8b6eb740ea"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8587afc0-1636-4243-9dde-21b70c1c59c4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""675a816c-730a-4dc3-99c9-ef7aef7b30fc"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d015976b-37ed-495f-ae65-3bb8c914ac35"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""21944295-91ac-41cb-8349-9d53ed47e61c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60f193a5-cfe8-4004-b796-184a142dedb5"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd83d380-4f11-4b02-a222-76ab62ad9feb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea969d95-4e82-4687-b9fa-6a5a3c98728c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""101ba3b4-b351-4f99-9263-83076960539e"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab87aa0c-8268-4e13-adcf-7ad6ec31d2ed"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b01b842-9b00-4de4-b3e1-9964530f871d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b73dbe22-19bd-4d2e-8023-1bbccf3591ee"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""e0c426c3-32f9-4af6-9ea0-34dcaf473b7b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c657bf48-1f2b-4283-a20c-a8852c264ff7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b200018c-6c0d-4331-a145-4ca54644cc9d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3c4b571d-a5ce-49fc-b30c-d2cda6e59bfe"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""701987d6-d84e-48b9-81e3-216ee241c2bd"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4af6683c-a63b-441e-bf3d-e68407319707"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""883333fe-00cc-4742-9cbb-11de7440481e"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""01df339e-f9b1-418b-81af-dbc6653f372d"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5d8e4a3a-d307-4a18-8248-b5bc92d0461d"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b7be55c4-0a94-488e-8b5b-7f2737dadd76"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""88900f33-080e-4c24-a07f-2f15cae25590"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5053041f-4218-4ef1-9969-2768260417ee"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1b8034fc-0887-4935-a2e7-c9b6ceaddaa8"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b48d75ec-712c-48d1-bc43-39722d30bfa8"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b02b1ee6-4e24-4e6a-ba52-c374678b008a"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""b4e6cc9d-3603-4bbb-a79b-a36538f7d7fd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4e89c93-48a0-4656-bca1-a94de5b78d3f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ee57ba46-a733-44c3-91c9-fa769973a3c9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""468331cd-7fed-41ae-9337-e318b10b05da"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""42658fb1-4fe1-43a6-b545-eb3fabf9bb6a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""82fe8f2a-3d9c-43b5-98ed-049ab8d5091b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""09016d56-5d23-48fa-96ec-54424195bb9d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""856aa4a5-e532-4fe2-af16-43287c31badd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5937cae5-737e-4936-a21a-23c4516ff46d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dcaf184a-4719-4899-87e8-773bcee4366a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccddf5c0-1ac1-4e62-8ea7-c3aba1127c74"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bac727e-fe2d-461c-a819-26be92311175"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25d154f5-79ae-4ef7-af1c-e01c8c68dd87"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""trackBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ButtonActions
        m_ButtonActions = asset.FindActionMap("ButtonActions", throwIfNotFound: true);
        m_ButtonActions_powerupaction = m_ButtonActions.FindAction("powerupaction", throwIfNotFound: true);
        m_ButtonActions_trackBall = m_ButtonActions.FindAction("trackBall", throwIfNotFound: true);
        m_ButtonActions_Navigate = m_ButtonActions.FindAction("Navigate", throwIfNotFound: true);
        m_ButtonActions_powerupaction2 = m_ButtonActions.FindAction("powerupaction2", throwIfNotFound: true);
        m_ButtonActions_driftbar = m_ButtonActions.FindAction("driftbar", throwIfNotFound: true);
        m_ButtonActions_driftbar2 = m_ButtonActions.FindAction("driftbar2", throwIfNotFound: true);
        m_ButtonActions_moving = m_ButtonActions.FindAction("moving", throwIfNotFound: true);
        m_ButtonActions_moving2 = m_ButtonActions.FindAction("moving2", throwIfNotFound: true);
        m_ButtonActions_pause = m_ButtonActions.FindAction("pause", throwIfNotFound: true);
        m_ButtonActions_Rocket = m_ButtonActions.FindAction("Rocket", throwIfNotFound: true);
        m_ButtonActions_Rocket2 = m_ButtonActions.FindAction("Rocket2", throwIfNotFound: true);
        m_ButtonActions_submit = m_ButtonActions.FindAction("submit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ButtonActions
    private readonly InputActionMap m_ButtonActions;
    private IButtonActionsActions m_ButtonActionsActionsCallbackInterface;
    private readonly InputAction m_ButtonActions_powerupaction;
    private readonly InputAction m_ButtonActions_trackBall;
    private readonly InputAction m_ButtonActions_Navigate;
    private readonly InputAction m_ButtonActions_powerupaction2;
    private readonly InputAction m_ButtonActions_driftbar;
    private readonly InputAction m_ButtonActions_driftbar2;
    private readonly InputAction m_ButtonActions_moving;
    private readonly InputAction m_ButtonActions_moving2;
    private readonly InputAction m_ButtonActions_pause;
    private readonly InputAction m_ButtonActions_Rocket;
    private readonly InputAction m_ButtonActions_Rocket2;
    private readonly InputAction m_ButtonActions_submit;
    public struct ButtonActionsActions
    {
        private @GameControls m_Wrapper;
        public ButtonActionsActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @powerupaction => m_Wrapper.m_ButtonActions_powerupaction;
        public InputAction @trackBall => m_Wrapper.m_ButtonActions_trackBall;
        public InputAction @Navigate => m_Wrapper.m_ButtonActions_Navigate;
        public InputAction @powerupaction2 => m_Wrapper.m_ButtonActions_powerupaction2;
        public InputAction @driftbar => m_Wrapper.m_ButtonActions_driftbar;
        public InputAction @driftbar2 => m_Wrapper.m_ButtonActions_driftbar2;
        public InputAction @moving => m_Wrapper.m_ButtonActions_moving;
        public InputAction @moving2 => m_Wrapper.m_ButtonActions_moving2;
        public InputAction @pause => m_Wrapper.m_ButtonActions_pause;
        public InputAction @Rocket => m_Wrapper.m_ButtonActions_Rocket;
        public InputAction @Rocket2 => m_Wrapper.m_ButtonActions_Rocket2;
        public InputAction @submit => m_Wrapper.m_ButtonActions_submit;
        public InputActionMap Get() { return m_Wrapper.m_ButtonActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ButtonActionsActions set) { return set.Get(); }
        public void SetCallbacks(IButtonActionsActions instance)
        {
            if (m_Wrapper.m_ButtonActionsActionsCallbackInterface != null)
            {
                @powerupaction.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction;
                @powerupaction.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction;
                @powerupaction.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction;
                @trackBall.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnTrackBall;
                @trackBall.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnTrackBall;
                @trackBall.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnTrackBall;
                @Navigate.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnNavigate;
                @powerupaction2.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction2;
                @powerupaction2.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction2;
                @powerupaction2.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPowerupaction2;
                @driftbar.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar;
                @driftbar.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar;
                @driftbar.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar;
                @driftbar2.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar2;
                @driftbar2.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar2;
                @driftbar2.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnDriftbar2;
                @moving.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving;
                @moving.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving;
                @moving.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving;
                @moving2.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving2;
                @moving2.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving2;
                @moving2.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnMoving2;
                @pause.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPause;
                @pause.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPause;
                @pause.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnPause;
                @Rocket.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket;
                @Rocket.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket;
                @Rocket.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket;
                @Rocket2.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket2;
                @Rocket2.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket2;
                @Rocket2.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnRocket2;
                @submit.started -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnSubmit;
                @submit.performed -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnSubmit;
                @submit.canceled -= m_Wrapper.m_ButtonActionsActionsCallbackInterface.OnSubmit;
            }
            m_Wrapper.m_ButtonActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @powerupaction.started += instance.OnPowerupaction;
                @powerupaction.performed += instance.OnPowerupaction;
                @powerupaction.canceled += instance.OnPowerupaction;
                @trackBall.started += instance.OnTrackBall;
                @trackBall.performed += instance.OnTrackBall;
                @trackBall.canceled += instance.OnTrackBall;
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @powerupaction2.started += instance.OnPowerupaction2;
                @powerupaction2.performed += instance.OnPowerupaction2;
                @powerupaction2.canceled += instance.OnPowerupaction2;
                @driftbar.started += instance.OnDriftbar;
                @driftbar.performed += instance.OnDriftbar;
                @driftbar.canceled += instance.OnDriftbar;
                @driftbar2.started += instance.OnDriftbar2;
                @driftbar2.performed += instance.OnDriftbar2;
                @driftbar2.canceled += instance.OnDriftbar2;
                @moving.started += instance.OnMoving;
                @moving.performed += instance.OnMoving;
                @moving.canceled += instance.OnMoving;
                @moving2.started += instance.OnMoving2;
                @moving2.performed += instance.OnMoving2;
                @moving2.canceled += instance.OnMoving2;
                @pause.started += instance.OnPause;
                @pause.performed += instance.OnPause;
                @pause.canceled += instance.OnPause;
                @Rocket.started += instance.OnRocket;
                @Rocket.performed += instance.OnRocket;
                @Rocket.canceled += instance.OnRocket;
                @Rocket2.started += instance.OnRocket2;
                @Rocket2.performed += instance.OnRocket2;
                @Rocket2.canceled += instance.OnRocket2;
                @submit.started += instance.OnSubmit;
                @submit.performed += instance.OnSubmit;
                @submit.canceled += instance.OnSubmit;
            }
        }
    }
    public ButtonActionsActions @ButtonActions => new ButtonActionsActions(this);
    public interface IButtonActionsActions
    {
        void OnPowerupaction(InputAction.CallbackContext context);
        void OnTrackBall(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnPowerupaction2(InputAction.CallbackContext context);
        void OnDriftbar(InputAction.CallbackContext context);
        void OnDriftbar2(InputAction.CallbackContext context);
        void OnMoving(InputAction.CallbackContext context);
        void OnMoving2(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRocket(InputAction.CallbackContext context);
        void OnRocket2(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
}
