//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""ButtonActions"",
            ""id"": ""a7f26d43-ca3e-4aca-9248-99362d0010c6"",
            ""actions"": [
                {
                    ""name"": ""powerupaction"",
                    ""type"": ""PassThrough"",
                    ""id"": ""421b8609-13e1-4749-8cf0-f0aa2ab731d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavigateP2Arcade"",
                    ""type"": ""Value"",
                    ""id"": ""1da28c6f-c4dc-4632-9a42-3ac3e74abc51"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavigateP2"",
                    ""type"": ""Value"",
                    ""id"": ""4953b2c0-bc96-44df-bc1f-268cdcd19269"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavigateP1"",
                    ""type"": ""Value"",
                    ""id"": ""f8620fd2-23fd-4b97-8e45-b7d0670da88f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""submitp1"",
                    ""type"": ""Button"",
                    ""id"": ""09eb2b08-cc3d-4f5d-bdf6-6bba5bcea91e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""submitp2"",
                    ""type"": ""Button"",
                    ""id"": ""d6ba141b-6e5d-4728-9913-622640c831d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""trackBall"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b4029cdc-7c4e-4be4-af75-0dfb40ccb394"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""powerupaction2"",
                    ""type"": ""Button"",
                    ""id"": ""75d00f2c-d190-4f8a-ad48-392ba3ff4ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""driftbar"",
                    ""type"": ""Button"",
                    ""id"": ""2037763c-0abf-46fd-ba65-8225675ac4b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpinBarLeft"",
                    ""type"": ""Button"",
                    ""id"": ""2d56c95f-e0a1-4c08-b8e6-fab6d8799dc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpinBarRight"",
                    ""type"": ""Button"",
                    ""id"": ""a69c7731-485a-47d9-b506-f5d5f89e990f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""driftbar2"",
                    ""type"": ""Button"",
                    ""id"": ""d07662cc-fa04-4c67-a42b-2d9931b365bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moving"",
                    ""type"": ""Value"",
                    ""id"": ""24eae9dd-3d6f-461d-952d-a394132dc575"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""moving2"",
                    ""type"": ""Value"",
                    ""id"": ""d7a5af90-2181-4c09-8b32-32b687707c5b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""pause"",
                    ""type"": ""Button"",
                    ""id"": ""bb89a99d-7ce2-4163-8640-16567146bfbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rocket"",
                    ""type"": ""Button"",
                    ""id"": ""7d5e5510-dcf8-4604-8530-a58752f7244b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rocket2"",
                    ""type"": ""Button"",
                    ""id"": ""7d2d8f79-1a83-46f7-bd26-02b8d1d028c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29a7c631-783c-472f-bfbe-2e836cb77930"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9f50701-9dad-4ee6-86f7-ac18290617de"",
                    ""path"": ""<SwitchProControllerHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f797cb0-7c06-49d5-a3bb-da5bc7f336a7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9ddad06-bde9-499f-b46a-6d44468a3440"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4225a425-aee5-4930-99d3-352ca8b9ac1e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""334ff061-416d-4509-ae08-c24c1d5735e0"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b37dbd39-787e-4df3-9191-25138f7798cf"",
                    ""path"": ""<SwitchProControllerHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8109c364-96f0-4071-8054-06c82fd3f8c3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f027d046-6a79-4151-b1bb-6082b3ab3ddf"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7674ac39-783d-4c5a-b6dd-f2e38aa0c7a7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ed723dc-08e4-4d78-90ca-2f79b977f0a4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""494ca615-96da-4647-bb10-ad76a2d9d86c"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5ebd891f-eba1-469d-89f2-3595234a5217"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""25f94f4e-3255-40ca-beaf-5b2fb5186e07"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bab2d4b6-1c7b-4c3d-ac4b-34f308304878"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2865de7c-cd10-4efb-a64e-f87a042bbaa2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b6b2ea75-da7c-4ced-a4c5-c312dfe27957"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c87e6310-3e83-4481-af04-2370393d3c10"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0a1b4043-f505-4678-b10d-03e9bcfd768a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""56116a91-beca-4b53-ab1a-d543c0a1e9ac"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5adad2f6-c61e-47a3-83b9-bb74f39ee51f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b1d2aa77-fa6c-454e-afd4-2e67da3dc145"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""476269e4-21a4-442f-8eda-72df4ca673ba"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50d8d104-d95e-4b51-b333-93c5de3be8fa"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9201907d-4a43-4e30-8f14-1aa6b37182b3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70ae3a56-c1b7-42a8-bdbc-83db8c7b2b30"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba4b1aae-e873-452b-b5b1-add0ba684a56"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""powerupaction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7322dcd8-adc6-4d5d-b989-c94ec7478552"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6164db55-71a5-491c-b8b7-33b52427a695"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74869ff1-fc8e-49b4-909d-1ee860a4fe43"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30840917-33d7-40dc-804e-95183afde131"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ff644ad-e607-4c25-8253-9ae8cb609bad"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""driftbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d58a777-2809-4afc-aa65-0ebb569d311c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5af59410-d30e-4667-a397-0d0ea327a452"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""661161b0-5441-4088-8ae8-be8b6eb740ea"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8587afc0-1636-4243-9dde-21b70c1c59c4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""675a816c-730a-4dc3-99c9-ef7aef7b30fc"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d015976b-37ed-495f-ae65-3bb8c914ac35"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""21944295-91ac-41cb-8349-9d53ed47e61c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60f193a5-cfe8-4004-b796-184a142dedb5"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd83d380-4f11-4b02-a222-76ab62ad9feb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea969d95-4e82-4687-b9fa-6a5a3c98728c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""101ba3b4-b351-4f99-9263-83076960539e"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab87aa0c-8268-4e13-adcf-7ad6ec31d2ed"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b01b842-9b00-4de4-b3e1-9964530f871d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b73dbe22-19bd-4d2e-8023-1bbccf3591ee"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25d154f5-79ae-4ef7-af1c-e01c8c68dd87"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""trackBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""8c2d644c-7cbf-4e0f-bf24-1b99af7b8b3e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2Arcade"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c6ebeba9-06ca-493f-860c-7556b2f7ae69"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2Arcade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e84b3e4d-4288-4c59-ba54-618aca66c3f4"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2Arcade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c334df58-4ce8-4515-9fac-ca1e36af2562"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2Arcade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ea131675-e43d-4f67-81fb-56a411cee8d7"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2Arcade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""85f39ab3-d441-4820-99de-ea47029dbd72"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""01184b17-ab77-4deb-90a8-13827643090e"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a3507240-989c-4885-8c5e-6b79f96854c2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""34ba059c-2025-431d-9168-48d1de438cc8"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""259e382e-6f26-4887-a9b6-c7dbfe249d3e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keypoard"",
                    ""id"": ""ddc4988f-d4c5-43b3-9136-4a08be36663a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""af0a423a-b85b-477f-9521-87c5075eb8ef"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""38e07214-99df-4681-981c-9da04580e29b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2177a01a-c939-4407-9652-3864b4cb924a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d26710a5-126a-4b28-9004-bf0085d76996"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""41773098-85a2-4680-9a7e-a9c33ef18025"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""23930093-9342-484f-ac26-d3ae800ce64c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b1798c20-ed0d-4b20-8c06-437fe0dd44f3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""633867ef-017e-4f57-a5c6-ed6971817b01"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""03c1d518-56d4-4aa8-86ac-696f7d2deca7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submitp2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daa5a991-d2c8-4f98-b242-a97e28d7bd24"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submitp2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a03049-24fd-4036-add3-fd879672bac4"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submitp2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ec7f33-a931-4da7-b67d-1a243aaffea0"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submitp1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abf3501c-e06b-4dbd-a39b-c203c02be7a6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submitp1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""51b528e0-b70b-427f-a91e-f6945f3c81e9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""42414f43-f01a-4cdc-8466-28d5f7f8030c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5159cfb-5e94-4f87-8679-6120dcfc4f11"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f3fed27c-f9bd-430b-b7dc-09826149756b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d2014f8e-eb3d-41c9-a415-e983a15ea8cf"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""112e4625-de22-4c04-9b0a-48384439f255"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b8714876-5f99-4d2f-825f-9c6dbd85c2e2"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7d51a01c-c7dd-44e6-ad5d-ae123b14acd6"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e3ba7c1d-2354-456f-93c8-2eda794f2cc8"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b011c494-1d7e-4130-9dcb-648ae738208f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinBarLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28f14b4e-2aa9-4d40-b52c-f81077c3e91a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinBarLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d00280bc-4014-415b-af67-75c68ad7ea4d"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinBarRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bcac202-3348-459c-8ac7-7059f3ff9d6a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinBarRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ButtonActions
        m_ButtonActions = asset.FindActionMap("ButtonActions", throwIfNotFound: true);
        m_ButtonActions_powerupaction = m_ButtonActions.FindAction("powerupaction", throwIfNotFound: true);
        m_ButtonActions_NavigateP2Arcade = m_ButtonActions.FindAction("NavigateP2Arcade", throwIfNotFound: true);
        m_ButtonActions_NavigateP2 = m_ButtonActions.FindAction("NavigateP2", throwIfNotFound: true);
        m_ButtonActions_NavigateP1 = m_ButtonActions.FindAction("NavigateP1", throwIfNotFound: true);
        m_ButtonActions_submitp1 = m_ButtonActions.FindAction("submitp1", throwIfNotFound: true);
        m_ButtonActions_submitp2 = m_ButtonActions.FindAction("submitp2", throwIfNotFound: true);
        m_ButtonActions_trackBall = m_ButtonActions.FindAction("trackBall", throwIfNotFound: true);
        m_ButtonActions_powerupaction2 = m_ButtonActions.FindAction("powerupaction2", throwIfNotFound: true);
        m_ButtonActions_driftbar = m_ButtonActions.FindAction("driftbar", throwIfNotFound: true);
        m_ButtonActions_SpinBarLeft = m_ButtonActions.FindAction("SpinBarLeft", throwIfNotFound: true);
        m_ButtonActions_SpinBarRight = m_ButtonActions.FindAction("SpinBarRight", throwIfNotFound: true);
        m_ButtonActions_driftbar2 = m_ButtonActions.FindAction("driftbar2", throwIfNotFound: true);
        m_ButtonActions_moving = m_ButtonActions.FindAction("moving", throwIfNotFound: true);
        m_ButtonActions_moving2 = m_ButtonActions.FindAction("moving2", throwIfNotFound: true);
        m_ButtonActions_pause = m_ButtonActions.FindAction("pause", throwIfNotFound: true);
        m_ButtonActions_Rocket = m_ButtonActions.FindAction("Rocket", throwIfNotFound: true);
        m_ButtonActions_Rocket2 = m_ButtonActions.FindAction("Rocket2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ButtonActions
    private readonly InputActionMap m_ButtonActions;
    private List<IButtonActionsActions> m_ButtonActionsActionsCallbackInterfaces = new List<IButtonActionsActions>();
    private readonly InputAction m_ButtonActions_powerupaction;
    private readonly InputAction m_ButtonActions_NavigateP2Arcade;
    private readonly InputAction m_ButtonActions_NavigateP2;
    private readonly InputAction m_ButtonActions_NavigateP1;
    private readonly InputAction m_ButtonActions_submitp1;
    private readonly InputAction m_ButtonActions_submitp2;
    private readonly InputAction m_ButtonActions_trackBall;
    private readonly InputAction m_ButtonActions_powerupaction2;
    private readonly InputAction m_ButtonActions_driftbar;
    private readonly InputAction m_ButtonActions_SpinBarLeft;
    private readonly InputAction m_ButtonActions_SpinBarRight;
    private readonly InputAction m_ButtonActions_driftbar2;
    private readonly InputAction m_ButtonActions_moving;
    private readonly InputAction m_ButtonActions_moving2;
    private readonly InputAction m_ButtonActions_pause;
    private readonly InputAction m_ButtonActions_Rocket;
    private readonly InputAction m_ButtonActions_Rocket2;
    public struct ButtonActionsActions
    {
        private @GameControls m_Wrapper;
        public ButtonActionsActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @powerupaction => m_Wrapper.m_ButtonActions_powerupaction;
        public InputAction @NavigateP2Arcade => m_Wrapper.m_ButtonActions_NavigateP2Arcade;
        public InputAction @NavigateP2 => m_Wrapper.m_ButtonActions_NavigateP2;
        public InputAction @NavigateP1 => m_Wrapper.m_ButtonActions_NavigateP1;
        public InputAction @submitp1 => m_Wrapper.m_ButtonActions_submitp1;
        public InputAction @submitp2 => m_Wrapper.m_ButtonActions_submitp2;
        public InputAction @trackBall => m_Wrapper.m_ButtonActions_trackBall;
        public InputAction @powerupaction2 => m_Wrapper.m_ButtonActions_powerupaction2;
        public InputAction @driftbar => m_Wrapper.m_ButtonActions_driftbar;
        public InputAction @SpinBarLeft => m_Wrapper.m_ButtonActions_SpinBarLeft;
        public InputAction @SpinBarRight => m_Wrapper.m_ButtonActions_SpinBarRight;
        public InputAction @driftbar2 => m_Wrapper.m_ButtonActions_driftbar2;
        public InputAction @moving => m_Wrapper.m_ButtonActions_moving;
        public InputAction @moving2 => m_Wrapper.m_ButtonActions_moving2;
        public InputAction @pause => m_Wrapper.m_ButtonActions_pause;
        public InputAction @Rocket => m_Wrapper.m_ButtonActions_Rocket;
        public InputAction @Rocket2 => m_Wrapper.m_ButtonActions_Rocket2;
        public InputActionMap Get() { return m_Wrapper.m_ButtonActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ButtonActionsActions set) { return set.Get(); }
        public void AddCallbacks(IButtonActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_ButtonActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ButtonActionsActionsCallbackInterfaces.Add(instance);
            @powerupaction.started += instance.OnPowerupaction;
            @powerupaction.performed += instance.OnPowerupaction;
            @powerupaction.canceled += instance.OnPowerupaction;
            @NavigateP2Arcade.started += instance.OnNavigateP2Arcade;
            @NavigateP2Arcade.performed += instance.OnNavigateP2Arcade;
            @NavigateP2Arcade.canceled += instance.OnNavigateP2Arcade;
            @NavigateP2.started += instance.OnNavigateP2;
            @NavigateP2.performed += instance.OnNavigateP2;
            @NavigateP2.canceled += instance.OnNavigateP2;
            @NavigateP1.started += instance.OnNavigateP1;
            @NavigateP1.performed += instance.OnNavigateP1;
            @NavigateP1.canceled += instance.OnNavigateP1;
            @submitp1.started += instance.OnSubmitp1;
            @submitp1.performed += instance.OnSubmitp1;
            @submitp1.canceled += instance.OnSubmitp1;
            @submitp2.started += instance.OnSubmitp2;
            @submitp2.performed += instance.OnSubmitp2;
            @submitp2.canceled += instance.OnSubmitp2;
            @trackBall.started += instance.OnTrackBall;
            @trackBall.performed += instance.OnTrackBall;
            @trackBall.canceled += instance.OnTrackBall;
            @powerupaction2.started += instance.OnPowerupaction2;
            @powerupaction2.performed += instance.OnPowerupaction2;
            @powerupaction2.canceled += instance.OnPowerupaction2;
            @driftbar.started += instance.OnDriftbar;
            @driftbar.performed += instance.OnDriftbar;
            @driftbar.canceled += instance.OnDriftbar;
            @SpinBarLeft.started += instance.OnSpinBarLeft;
            @SpinBarLeft.performed += instance.OnSpinBarLeft;
            @SpinBarLeft.canceled += instance.OnSpinBarLeft;
            @SpinBarRight.started += instance.OnSpinBarRight;
            @SpinBarRight.performed += instance.OnSpinBarRight;
            @SpinBarRight.canceled += instance.OnSpinBarRight;
            @driftbar2.started += instance.OnDriftbar2;
            @driftbar2.performed += instance.OnDriftbar2;
            @driftbar2.canceled += instance.OnDriftbar2;
            @moving.started += instance.OnMoving;
            @moving.performed += instance.OnMoving;
            @moving.canceled += instance.OnMoving;
            @moving2.started += instance.OnMoving2;
            @moving2.performed += instance.OnMoving2;
            @moving2.canceled += instance.OnMoving2;
            @pause.started += instance.OnPause;
            @pause.performed += instance.OnPause;
            @pause.canceled += instance.OnPause;
            @Rocket.started += instance.OnRocket;
            @Rocket.performed += instance.OnRocket;
            @Rocket.canceled += instance.OnRocket;
            @Rocket2.started += instance.OnRocket2;
            @Rocket2.performed += instance.OnRocket2;
            @Rocket2.canceled += instance.OnRocket2;
        }

        private void UnregisterCallbacks(IButtonActionsActions instance)
        {
            @powerupaction.started -= instance.OnPowerupaction;
            @powerupaction.performed -= instance.OnPowerupaction;
            @powerupaction.canceled -= instance.OnPowerupaction;
            @NavigateP2Arcade.started -= instance.OnNavigateP2Arcade;
            @NavigateP2Arcade.performed -= instance.OnNavigateP2Arcade;
            @NavigateP2Arcade.canceled -= instance.OnNavigateP2Arcade;
            @NavigateP2.started -= instance.OnNavigateP2;
            @NavigateP2.performed -= instance.OnNavigateP2;
            @NavigateP2.canceled -= instance.OnNavigateP2;
            @NavigateP1.started -= instance.OnNavigateP1;
            @NavigateP1.performed -= instance.OnNavigateP1;
            @NavigateP1.canceled -= instance.OnNavigateP1;
            @submitp1.started -= instance.OnSubmitp1;
            @submitp1.performed -= instance.OnSubmitp1;
            @submitp1.canceled -= instance.OnSubmitp1;
            @submitp2.started -= instance.OnSubmitp2;
            @submitp2.performed -= instance.OnSubmitp2;
            @submitp2.canceled -= instance.OnSubmitp2;
            @trackBall.started -= instance.OnTrackBall;
            @trackBall.performed -= instance.OnTrackBall;
            @trackBall.canceled -= instance.OnTrackBall;
            @powerupaction2.started -= instance.OnPowerupaction2;
            @powerupaction2.performed -= instance.OnPowerupaction2;
            @powerupaction2.canceled -= instance.OnPowerupaction2;
            @driftbar.started -= instance.OnDriftbar;
            @driftbar.performed -= instance.OnDriftbar;
            @driftbar.canceled -= instance.OnDriftbar;
            @SpinBarLeft.started -= instance.OnSpinBarLeft;
            @SpinBarLeft.performed -= instance.OnSpinBarLeft;
            @SpinBarLeft.canceled -= instance.OnSpinBarLeft;
            @SpinBarRight.started -= instance.OnSpinBarRight;
            @SpinBarRight.performed -= instance.OnSpinBarRight;
            @SpinBarRight.canceled -= instance.OnSpinBarRight;
            @driftbar2.started -= instance.OnDriftbar2;
            @driftbar2.performed -= instance.OnDriftbar2;
            @driftbar2.canceled -= instance.OnDriftbar2;
            @moving.started -= instance.OnMoving;
            @moving.performed -= instance.OnMoving;
            @moving.canceled -= instance.OnMoving;
            @moving2.started -= instance.OnMoving2;
            @moving2.performed -= instance.OnMoving2;
            @moving2.canceled -= instance.OnMoving2;
            @pause.started -= instance.OnPause;
            @pause.performed -= instance.OnPause;
            @pause.canceled -= instance.OnPause;
            @Rocket.started -= instance.OnRocket;
            @Rocket.performed -= instance.OnRocket;
            @Rocket.canceled -= instance.OnRocket;
            @Rocket2.started -= instance.OnRocket2;
            @Rocket2.performed -= instance.OnRocket2;
            @Rocket2.canceled -= instance.OnRocket2;
        }

        public void RemoveCallbacks(IButtonActionsActions instance)
        {
            if (m_Wrapper.m_ButtonActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IButtonActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_ButtonActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ButtonActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ButtonActionsActions @ButtonActions => new ButtonActionsActions(this);
    public interface IButtonActionsActions
    {
        void OnPowerupaction(InputAction.CallbackContext context);
        void OnNavigateP2Arcade(InputAction.CallbackContext context);
        void OnNavigateP2(InputAction.CallbackContext context);
        void OnNavigateP1(InputAction.CallbackContext context);
        void OnSubmitp1(InputAction.CallbackContext context);
        void OnSubmitp2(InputAction.CallbackContext context);
        void OnTrackBall(InputAction.CallbackContext context);
        void OnPowerupaction2(InputAction.CallbackContext context);
        void OnDriftbar(InputAction.CallbackContext context);
        void OnSpinBarLeft(InputAction.CallbackContext context);
        void OnSpinBarRight(InputAction.CallbackContext context);
        void OnDriftbar2(InputAction.CallbackContext context);
        void OnMoving(InputAction.CallbackContext context);
        void OnMoving2(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRocket(InputAction.CallbackContext context);
        void OnRocket2(InputAction.CallbackContext context);
    }
}
